---
# deployement de Kubernetes
- hosts: 15.188.119.181 an

  become: yes
  tasks:
    - name: Installer les dependences
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Ajouter le référentiel Kubernetes
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present

    - name: Importer la clé de signature GPG de Kubernetes
      shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
      ignore_errors: yes

    - name: Installer kubeadm, kubelet et kubectl
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - docker-ce
        - kubelet
        - kubeadm
        - kubectl

    - name: Initialiser le cluster Kubernetes avec kubeadm
      command: kubeadm init --apiserver-advertise-address={{ ansible_host }}
      args:
        creates: /etc/kubernetes/admin.conf
      register: kubeadm_init
      when: not kubeadm_init.changed

    - name: Copier la configuration du cluster pour l'utilisateur
      command: cp /etc/kubernetes/admin.conf /home/{{ ansible_user }}/.kube/config
      args:
        creates: /home/{{ ansible_user }}/.kube/config
      when: not kubeadm_init.changed
